name       : python-mechanize
version    : 0.4.3
release    : 4
source     :
    - https://github.com/python-mechanize/mechanize/archive/v0.4.3.tar.gz : 7c452a3eed7f83a13674027a58a4afe57ca67630d252a789ac1c15dcd55d310c
license    :
    - BSD-3-Clause
    - ZPL-2.1
component  : programming.python
summary    : Python Mechanize Module
description: |
    Stateful programmatic web browsing in Python, after Andy Lester’s Perl module WWW::Mechanize.
builddeps  :
    - python-html5lib
    - python-twisted
rundeps    :
    - python-html5lib
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
