name       : python-mechanize
version    : 0.2.5
release    : 2
source     :
    - http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.5.tar.gz : 2e67b20d107b30c00ad814891a095048c35d9d8cb9541801cebe85684cc84766
license    :
    - BSD-3-Clause
    - ZPL-2.1
summary    : Python Mechanize Module
description: |
    Stateful programmatic web browsing in Python, after Andy Lester’s Perl module WWW::Mechanize.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
    - python3-setuptools
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
