name       : python-mechanize
version    : 0.4.7
release    : 7
source     :
    - https://github.com/python-mechanize/mechanize/archive/v0.4.7.tar.gz : 993da15561d335d9a6423d17c790e62dcfe92d7de620b3244fbd7a8efc422404
homepage   : https://github.com/python-mechanize/mechanize
license    :
    - BSD-3-Clause
    - ZPL-2.1
component  : programming.python
summary    : Python Mechanize Module
description: |
    Stateful programmatic web browsing in Python, after Andy Lester’s Perl module WWW::Mechanize.
builddeps  :
    - python-html5lib
    - python-twisted
rundeps    :
    - python-html5lib
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
