name       : python-mechanize
version    : 0.4.8
release    : 9
source     :
    - https://github.com/python-mechanize/mechanize/archive/v0.4.8.tar.gz : f8003f80a3fa191ce2e9b40717617d10fc2aa7a1119881cd78588cd1b5e24cfb
homepage   : https://github.com/python-mechanize/mechanize
license    :
    - BSD-3-Clause
    - ZPL-2.1
component  : programming.python
summary    : Python Mechanize Module
description: |
    Stateful programmatic web browsing in Python, after Andy Lester’s Perl module WWW::Mechanize.
builddeps  :
    - python-html5lib
    - python-twisted
rundeps    :
    - python-html5lib
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test run_tests.py
