name       : python-mechanize
version    : 0.3.6
release    : 3
source     :
    - https://github.com/python-mechanize/mechanize/archive/v0.3.6.tar.gz : 377ca7b2160716857a2035d986abba1c133f4f80939c19002333c82bd4c01e98
license    :
    - BSD-3-Clause
    - ZPL-2.1
component  : programming.python
summary    : Python Mechanize Module
description: |
    Stateful programmatic web browsing in Python, after Andy Lester’s Perl module WWW::Mechanize.
builddeps  :
    - python-html5lib
    - python-setuptools
    - python-twisted
    - python-zope.interface
rundeps    :
    - python-html5lib
build      : |
    %python_setup
install    : |
    %python_install
#check      : |
#    pushd $PKG_BUILD_DIR/py2build
#        python run_tests.py
#    popd
